### ISSUE TITLE
Environment variables for database connections strings seems to be wrong

### ISSUE THREAD

**Issue by ghost** [testdrivenio/testdriven-kubernetes-app#16]
I was working on your "Microservice with Docker, Flask, and React"-Tutorial and I still finished the Test Setup chapter from part 1.

When I'm executing the defined tests I became the following error:
```
ERROR: test_users (test_users.TestUserService)
Ensure the /ping route behaves correctly

Traceback (most recent call last):
  File "/usr/src/app/project/tests/base.py", line 11, in setUp
    db.create_all()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 560, in get_engine
    options = self.get_options(sa_url, echo)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 575, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 877, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'

```
I think it has to do with the configured database connection strings (DATABASE_URL & DATABASE_TEST_URL) within the docker-compose.yaml:
```
version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev  # new
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test  # new
    depends_on:  # new
      - users-db

  users-db:  # new
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
```
According to https://docs.sqlalchemy.org/en/13/core/engines.html#postgresql it must be 'postgresql' instead of 'postgres' as the used dialect.

**Comment by mjhea0** [comment]
Did that fix it?

**Comment by ghost** [comment]
Yes, it did 👍

**Comment by mjhea0** [comment]
Awesome. Feel free to email me directly with questions in the future. michael at testdriven dot io.
